### PR TITLE
Turns out canvas_course_admin_tools (ccat) has been deprecated and is…

### PR DESCRIPTION
**Pull request by hktest**
… used only for the course import too.  Moving all the selenium changed files in the ccat project to the new canvas_manage_course project.

Tested locally.

### CODE REVIEW

**Comment by hktest** [comment]
No additional PR required. Already PRed in the other project.

- Will set up the Jenkins test for this project before merge.
- Will need to delete the selenium tests from the other projects once this one is run successfully.

**Comment by elliottyates** [comment]
👍  - do we want to bring the Manage People and dashboard tests over in (a) separate PR(s)?

**Comment by hktest** [comment]
@elliottyates, unless I am reading it wrong, it looks like those tests have been moved over to the new project (the whole project was copied over at a certain time last week, I think, including selenium tests that existed at that time).   this is what I am seeing on develop: https://github.com/Harvard-University-iCommons/canvas_manage_course/tree/develop/selenium_tests  (so in this PR, I only moved over what hasn't been moved over...so I think we're covered?)

**Comment by elliottyates** [comment]
You're reading it perfectly right. :) Thanks! We're good.

**Pull request merged**
